# raise NameError('HiThere')

# try:
#     raise NameError('HiThere')
# raise NameError('HiThere')
#     print('An exception flew by!')
#     raise